version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:5000"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_database_name
      POSTGRES_USER: your_postgres_username
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"

volumes:
  db-data: